name: news_app_clean_architecture
description: "A clean architecture-based news application built with Flutter."
publish_to: 'none' # Prevents publishing to pub.dev
version: 0.1.0 # Initial version of the app

environment:
  sdk: ^3.6.0 # Specifies the Dart SDK version required for the app

dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style design
  cupertino_icons: ^1.0.2

  # State management
  flutter_bloc: ^8.1.6

  # Comparing Dart objects easily
  equatable: ^2.0.5

  # Dependency injection / service locator
  get_it: ^8.0.3

  # Date formatting and internationalization
  intl: ^0.20.1

  # Local database
  floor: ^1.4.2

  # Networking libraries
  retrofit: ^4.4.1 # Retrofit for API communication
  dio: ^5.7.0 # Dio HTTP client for making requests

  # Hooks for better state management and lifecycle handling
  flutter_hooks: ^0.20.5

  # Cached images for better performance
  cached_network_image: ^3.2.0

  # Functional programming tools
  dartz: ^0.10.1

  # Code generation for immutable classes and JSON serialization
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0

  # UI appearance customization
  appearance: ^0.0.1

  # Launching URLs
  url_launcher: ^6.2.4

  # SQLite database driver
  sqflite: ^2.4.1

  # Sharing content
  share_plus: ^10.1.3

  # Core Bloc package
  bloc: ^8.1.4

  # Declarative navigation
  go_router: ^14.6.2

  # Environment variable management
  flutter_dotenv: ^5.0.2

dev_dependencies:
  # Testing framework
  flutter_test:
    sdk: flutter

  # Flutter linting rules
  flutter_lints: ^5.0.0

  # Code generators
  retrofit_generator: ^9.1.5 # Generates Retrofit API client
  floor_generator: ^1.5.0 # Generates Floor database entities and DAOs
  build_runner: ^2.4.14 # Required for code generation
  freezed: ^2.3.0 # Generates immutable data classes
  json_serializable: ^6.3.1 # Generates JSON serialization code

flutter:
  uses-material-design: true # Enables Material Design icons

  # Environment file
  assets:
    - .env # Includes the .env file for managing API keys and environment variables

  # Custom fonts
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
